### PR TITLE
Refactoring for Windows build (clementine branch circleci-mingw)

### PR DESCRIPTION
**Pull request by JulianVolodia**

### CODE REVIEW

**Comment by JulianVolodia** [comment]
@hatstand , now build fails on gstreamer.
```
In file included from lex.priv_gst_parse_yy.c:2:0:
../../config.h:540:19: error: two or more data types in declaration specifiers
 #define clockid_t int
                   ^
Makefile:610: recipe for target 'libgstparse_la-lex.priv_gst_parse_yy.lo' failed
make[6]: *** [libgstparse_la-lex.priv_gst_parse_yy.lo] Error 1
```
I will have a look but for now only this repo was refactored (minor change on my fork of clementine for acquiring my Dependencies fork during CircleCI workflow).

**Comment by JulianVolodia** [comment]
btw. @hatstand do you recognize this error? Fast lookup for this bug didn't got me anywhere.

**Comment by hatstand** [comment]
Seems like a bug where it's trying to define `clockid_t` as it doesn't exist on windows, but it does exist in mingw. Probably needs an `#if MINGW` or something.

**Comment by hatstand** [comment]
Figured it out in https://github.com/clementine-player/Dependencies/commit/6b7bbd63a92f40eecb88ac0b93d280aa4182b131

**Pull request merged**
