### PR TITLE
Update Windows dependencies

### LINKED ISSUE #9: wavpack support
see https://github.com/clementine-player/Clementine/issues/3003

MXE (https://github.com/mxe/mxe) version of Clementine (https://github.com/mxe/mxe/blob/master/plugins/apps/clementine_qt4.mk) successfully plays the files in the format * .wv (but doesn't play iso.wv). MXE version of Clementine use this list of gstreamer-plugins https://github.com/clementine-player/Dependencies/blob/2c2963fb774bb9f67dbb8b7b903a32f0faeac66d/windows/Makefile#L92-L131

MXE use special utility copydlldeps.sh (https://github.com/mxe/mxe/blob/master/tools/copydlldeps.sh) to automatically calculate of dependencies. 

The copydlldeps.sh found that gstreamer-plugin libgstwavpack.dll https://github.com/clementine-player/Dependencies/blob/2c2963fb774bb9f67dbb8b7b903a32f0faeac66d/windows/Makefile#L130 has a dependency on libwavpack-1.dll and has copied libwavpack-1.dll to the install directory. The official release Clementine-1.3.1 doesn't contain files libwavpack-1.dll and libgstwavpack.dll.

### LINKED ISSUE #10: [Windows] Sqlite3 build broken
Sqlite3 won't build the requested file `libsqlite3-0.dll` file which should be copied in the build script at https://github.com/clementine-player/Dependencies/blob/master/windows/Makefile#L186

Branch: master

### PR DESCRIPTION
**Pull request by jonaski**
This updates most of the dependencies to the latest versions.
glib, glib-networking and orc are updated to the latest versions that still uses GNU configure, newer versions requires more work since they have switched to meson. libsoup is at the latest version with GNU configure.
I have built Clementine in debug with console and made sure that everything works and that all gstreamer plugins are loaded. I used openSUSE tumbleweed.
I have also tested that everything builds in CircleCI. Had to switch the download URL so the CI can build it, you can switch this back when you have updated the packages.
Had to change the LDFLAGS for sqlite to make libtool work.
I will open a PR in Clementine to update the NSI, it also fixes opus and wavpack support.

Fixes #10
Fixes #9

### CODE REVIEW

**Comment by hatstand** [comment]
CI didn't seem to run. Is it configured for your fork too?

**Comment by jonaski** [comment]
I removed the configuration from my own CircleCI before submitting the PR, but maybe I need to create a new branch. I can try a new branch.

**Comment by jonaski** [comment]
The fork is unfollowed in my CircleCI account, still doesn't run here.
@jbroadus do you know why?

**Comment by jonaski** [comment]
Perhaps it's a delay, I'll try again to tomorrow. Or you can just merge it without, it did succeed in my own CircleCI.

**Comment by jbroadus** [comment]
I'm not sure. I think I unfollowed, disabled the github triggers, then pushed a new change to the branch.

**Comment by hatstand** [comment]
@jonaski  I gave you permissions on the dependencies bucket here: https://console.cloud.google.com/storage/browser/clementine-data.appspot.com?forceOnBucketsSortingFiltering=false&project=clementine-data

No idea if it'll work 🤷

**Pull request merged**
