### PR TITLE
Update dependencies in general and add macOS Sierra/Xcode 8.0 compatibility

### PR DESCRIPTION
**Pull request by kth5**
I've been having issues with Clementine on Sierra including stuttering of fullscreen visualizations and slow opening of the application in general on a mid-2015 MBP 15". To verify whether or not a rebuild would fix some issues I tackled the issue and encountered tons of outdated libraries in use in this package. I updated where updates where due to the latest stable versions.

Additionally this includes:
* updates all dependencies for Windows and Mac builds in good faith
* new patch for Qt to replace use of API deprecated in 10.6 Snow Leopard and removed in Sierra
  * added local OpenSSL build for Qt does not cope well with OpenSSL shipped with Sierra
* working bison installed from Homebrew
* optional (but automagically enabled) ccache support if installed via Homebrew

The build guide still applies as I tried to ensure not breaking things along the way.

DISCLAMER:
Since I could not add files to the original Google Drive folder from where sources are downloaded, I created my own. Please fix downloader/downloader.py back to the original once you downloaded the sources.

### CODE REVIEW

**Comment by hatstand** [comment]
I think I uploaded all of the new files, can you fix the folder id and check?

Thanks for doing this. I guess it will break some stuff on windows but we can fix that afterwards.

**Comment by kth5** [comment]
How about this, in order not to break the windows stuff until either we or someone else looked at it, we create a new branch and I re-target my PR?

I'll also look at the Windows build today and see how far I can get.

**Comment by hatstand** [comment]
Yep, merging into a branch makes sense. We can still manually check it on the buildbot from there.

**Comment by kth5** [comment]
As I'm already halfway through with fixing up the Windows bits, let's create an testing branch. Already committed half to my master unfortunately.

**Comment by ArnaudBienner** [comment]
I broke Windows dependencies build with commit 36331d879a6a5fa21b4c1cb7ea438e28d9c7af43 and didn't have the time to fix this. So this might actually fix the Windows the build :)

**Comment by kth5** [comment]
Actually have all the dependencies build but Clementine itself fails during the link stage with the Spotify blob, so I'm currently looking at that.

In the meantime, I also upgraded the chroot to use Xenial the and the provided i686-w64-mingw32 toolchain. Thus I may have inadvertently broke it again. ;)

**Comment by kth5** [comment]
If either of you have an idea about this one? I think it's the only thing I haven't been able to get past for the Windows build yet at this point.

The make VERBOSE=1 log for my Clementine build:

`[ 98%] Linking CXX executable ../../clementine-spotifyblob.exe
cd /home/kth5/Clementine/bin/ext/clementine-spotifyblob && /usr/bin/cmake -E cmake_link_script CMakeFiles/clementine-spotifyblob.dir/link.txt --verbose=1
/usr/bin/ccache /usr/bin/cmake -E remove -f CMakeFiles/clementine-spotifyblob.dir/objects.a
/usr/bin/ccache /usr/bin/i686-w64-mingw32-ar cr CMakeFiles/clementine-spotifyblob.dir/objects.a @CMakeFiles/clementine-spotifyblob.dir/objects1.rsp
/usr/bin/ccache /usr/bin/i686-w64-mingw32-g++   -Woverloaded-virtual -Wall -Wno-sign-compare -Wno-deprecated-declarations -Wno-unused-local-typedefs -Wno-unused-private-field -Wno-unknown-warning-option --std=c++0x -U__STRICT_ANSI__ -O3 -DNDEBUG  -mwindows -Wl,--whole-archive CMakeFiles/clementine-spotifyblob.dir/objects.a -Wl,--no-whole-archive  -o ../../clementine-spotifyblob.exe -Wl,--out-implib,../../libclementine-spotifyblob.dll.a -Wl,--major-image-version,0,--minor-image-version,0 @CMakeFiles/clementine-spotifyblob.dir/linklibs.rsp
../libclementine-common/liblibclementine-common.a(logging.cpp.obj):logging.cpp:(.text+0x105): undefined reference to `_imp___ZN9QIODeviceC2Ev'
../libclementine-common/liblibclementine-common.a(logging.cpp.obj):logging.cpp:(.text+0x1c3): undefined reference to `_imp___Z18qInstallMsgHandlerPFv9QtMsgTypePKcE'
../libclementine-common/liblibclementine-common.a(logging.cpp.obj):logging.cpp:(.text+0x257): undefined reference to `_imp___ZN5QCharC1Ec'
../libclementine-common/liblibclementine-common.a(logging.cpp.obj):logging.cpp:(.text+0x28e): undefined reference to `_imp___ZNK7QString7indexOfE5QChariN2Qt15CaseSensitivityE'
../libclementine-common/liblibclementine-common.a(logging.cpp.obj):logging.cpp:(.text+0x2d9): undefined reference to `_imp___ZNK7QString11lastIndexOfERKS_iN2Qt15CaseSensitivityE'
../libclementine-common/liblibclementine-common.a(logging.cpp.obj):logging.cpp:(.text+0x316): undefined reference to `_imp___ZNK7QString4leftEi'
../libclementine-common/liblibclementine-common.a(logging.cpp.obj):logging.cpp:(.text+0x36f): undefined reference to `_imp___ZNK7QString11lastIndexOfE5QChariN2Qt15CaseSensitivityE'
../libclementine-common/liblibclementine-common.a(logging.cpp.obj):logging.cpp:(.text+0x395): undefined reference to `_imp___ZNK7QString3midEii'
../libclementine-common/liblibclementine-common.a(logging.cpp.obj):logging.cpp:(.text+0x408): undefined reference to `_imp___ZNK7QString4leftEi'
../libclementine-common/liblibclementine-common.a(logging.cpp.obj):logging.cpp:(.text+0x700): undefined reference to `_imp___ZN7QRegExpC1ERK7QStringN2Qt15CaseSensitivityENS_13PatternSyntaxE'
../libclementine-common/liblibclementine-common.a(logging.cpp.obj):logging.cpp:(.text+0x732): undefined reference to `_imp___ZNK7QString7indexOfER7QRegExpi'
../libclementine-common/liblibclementine-common.a(logging.cpp.obj):logging.cpp:(.text+0x753): undefined reference to `_imp___ZN7QRegExpD1Ev'
../libclementine-common/liblibclementine-common.a(logging.cpp.obj):logging.cpp:(.text+0x78a): undefined reference to `_imp___ZN7QRegExp3capEi'
../libclementine-common/liblibclementine-common.a(logging.cpp.obj):logging.cpp:(.text+0x85b): undefined reference to `_imp___ZN7QRegExpD1Ev'
../libclementine-common/liblibclementine-common.a(logging.cpp.obj):logging.cpp:(.text+0x97a): undefined reference to `_imp___ZNK7QString3argExiiRK5QChar'
../libclementine-common/liblibclementine-common.a(logging.cpp.obj):logging.cpp:(.text+0x9a9): undefined reference to `_imp___ZNK7QString3argERKS_iRK5QChar'
../libclementine-common/liblibclementine-common.a(logging.cpp.obj):logging.cpp:(.text+0x9f8): undefined reference to `_imp___ZN11QTextStreamlsEc'
../libclementine-common/liblibclementine-common.a(logging.cpp.obj):logging.cpp:(.text+0xa27): undefined reference to `_imp___ZN11QTextStreamlsERK7QString'
../libclementine-common/liblibclementine-common.a(logging.cpp.obj):logging.cpp:(.text+0xc53): undefined reference to `_imp___ZN5QCharC1Ec'
../libclementine-common/liblibclementine-common.a(logging.cpp.obj):logging.cpp:(.text+0xc97): undefined reference to `_imp___ZNK7QString5splitERK5QCharNS_13SplitBehaviorEN2Qt15CaseSensitivityE'`

**Comment by ArnaudBienner** [comment]
Seems like it cannot find some Qt symbols, but I'm not sure why...
Looks like command line doesn't mention Qt indeed, but I'm not sure if that's hidden or really missing..

**Comment by kth5** [comment]
The last call that makes things fail translates to this:

>/usr/bin/i686-w64-mingw32-g++   -Woverloaded-virtual -Wall -Wno-sign-compare -Wno-deprecated-declarations -Wno-unused-local-typedefs -Wno-unused-private-field -Wno-unknown-warning-option --std=c++0x -U__STRICT_ANSI__ -O3 -DNDEBUG  -mwindows -Wl,--whole-archive CMakeFiles/clementine-spotifyblob.dir/objects.a -Wl,--no-whole-archive  -o ../../clementine-spotifyblob.exe -Wl,--out-implib,../../libclementine-spotifyblob.dll.a -Wl,--major-image-version,0,--minor-image-version,0 -L/target/lib  /target/lib/libspotify.lib /target/lib/libQtCore4.a /target/lib/libQtNetwork4.a -lgstbase-1.0 -lgstreamer-1.0 -lgobject-2.0 -lglib-2.0 -lintl -lgstapp-1.0 -lgstbase-1.0 -lgstreamer-1.0 -lgobject-2.0 -lglib-2.0 -lintl /target/lib/libprotobuf.a ../libclementine-spotifyblob/libclementine-spotifyblob-messages.a ../libclementine-common/liblibclementine-common.a -lgstapp-1.0 /target/lib/libprotobuf.a -ltag -lpthread -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32

QtCore4 and QtNetwork4 are there and so is spotify.

**Comment by kth5** [comment]
I'm done with getting all dependencies to build properly using the native Ubuntu Xenial MinGW offering as well as the old toolchain. I found an issue I cannot seem to bypass yet, Qt is simply not picked up by the spotifyblob bit unless I add: 
> -lQtCore4 -lQtNetwork4

to

>ext/clementine-spotifyblob/CMakeFiles/clementine-spotifyblob.dir/linklibs.rsp

after configuring with cmake like so:

>PKG_CONFIG_LIBDIR=/target/lib/pkgconfig  cmake ../ -DCMAKE_TOOLCHAIN_FILE=/src/Toolchain-mingw32.cmake -DPROTOBUF_PROTOC_EXECUTABLE=/target/bin/protoc

Qt is being linked properly everywhere else though. Need to figure it out still.

Then there is a biting issue I encountered with the threading model enabled in the toolchain used for the build. It seems the MinGW in the build doc and Ubuntu's differ. I'll recommend using the win32/windows thread model cos otherwise shipping more DDLs with the package will become necessary.

**Comment by prometheusdept** [comment]
Ok, fixing this one up more indepth and reopen using a branch as originally agreed upon. For now will close this PR.

**Comment by kth5** [comment]
Will fix the build on Windows and have to do some more work on Sierra as the beta releases ended up introducing further complications.

Will open a new PR and close this one for now.

**Pull request closed without merging**
